# 画像変換プログラムの設定ファイル

# リモートサーバー設定
remote:
  # リモート変換を有効/無効
  enabled: false
  # リモートサーバーのホスト名またはIPアドレス
  host: "example.com"
  # SSHポート
  port: 22
  # リモートユーザー名
  user: "webuser"
  # 秘密鍵のパス（空の場合はSSH Agentを使用）
  key_path: ""
  # 既知のホストファイルのパス（空の場合は検証を無効化）
  known_hosts: "~/.ssh/known_hosts"
  # リモートサーバー上の変換対象パス
  remote_path: "/var/www/html/images"
  # SSH Agentを使用するかどうか
  use_ssh_agent: true
  # タイムアウト（秒）
  timeout: 60

# 実行モード設定
mode:
  # ドライラン（true=実際の変換を行わず、ログのみ出力）
  dry_run: false

# 入力設定
input:
  # 画像を検索するディレクトリ
  directory: "./images"
  # サポートする拡張子（変換対象ファイル形式）
  supported_extensions:
    - .jpg
    - .jpeg
    - .png
    - .heic
    - .heif

# 変換設定
conversion:
  # 並列処理するワーカー数
  workers: 4
  # WebP変換設定
  webp:
    # 変換を有効/無効
    enabled: true
    # 画質設定（0-100）
    quality: 80
    # 圧縮レベル（0-6、値が大きいほど圧縮率が高い）
    compression_level: 4
  # AVIF変換設定
  avif:
    # 変換を有効/無効
    enabled: true
    # 画質設定（1-63）
    # 高品質: 40-63
    # 標準品質: 20-40
    # 低品質: 1-20
    quality: 40
    # 速度設定（0-10、値が小さいほど品質が高いが処理は遅くなる）
    # 0=最高品質/最低速度、10=最低品質/最高速度
    speed: 6
    # ロスレス圧縮（trueの場合、qualityは無視される）
    lossless: false

# FTPサーバー設定
ftp:
  # FTPサーバーを有効/無効
  enabled: false
  # FTPサーバーのポート
  port: 2121
  # FTPユーザー設定
  user:
    # ユーザー名
    name: "ftpuser"
    # パスワード（本番環境では平文で保存しないでください）
    password: "ftppassword"
  # パッシブモード設定
  passive:
    # パッシブモードを有効/無効
    enabled: true
    # パッシブポート範囲
    port_range: "50000-50100"

# SSHサーバー設定
ssh:
  # SSHサーバーを有効/無効
  enabled: false
  # SSHサーバーのポート
  port: 2222
  # SSH認証設定
  auth:
    # パスワード認証を有効/無効
    password_auth: true
    # 公開鍵認証（常に有効、ssh-agentの登録済み鍵が使用されます）
    # 以下の設定は下位互換性のために残していますが、実際には使用されません
    pubkey_auth: true
    auth_keys_file: "~/.ssh/authorized_keys"

# ログ設定
logging:
  # ログレベル（debug, info, warn, error）
  level: "info"
  # ログファイルの出力先（空の場合は自動生成）
  file: ""
  # ログファイルの最大サイズ（MB）
  max_size: 10
  # 保持するログファイルの数
  max_backups: 3
  # ログファイルの最大保持日数
  max_age: 28
  # ログを圧縮するかどうか
  compress: true
